swagger: "2.0"

info:
  version: "0.0.1"
  title: HomeAutomation API

basePath: /api/v1

schemes:
  - http

consumes:
  - application/json

produces:
  - application/json

paths: {}

definitions:
  Error:
    required:
      - status
      - message
    properties:
      status:
        description: HTTPステータスコード
        type: integer
      message:
        description: エラーメッセージ
        type: string
