openapi: 3.0.0
info:
  version: 0.0.2
  title: HomeAutomation API
paths: {}
servers:
  - url: /api/v1
components:
  schemas:
    Error:
      required:
        - status
        - messages
      properties:
        status:
          description: HTTPステータスコード
          type: integer
        messages:
          description: エラーメッセージの配列
          type: string
