openapi: 3.0.0
info:
  version: 0.0.2
  title: HomeAutomation API
paths:
  /aircon:
    get:
      description: エアコンを操作します
      operationId: aircon
      parameters:
        - name: power
          in: query
          description: 電源
          required: true
          schema:
            type: boolean
        - name: mode
          in: query
          required: false
          description: 運転モード (デフォルト Auto)
          schema:
            type: string
            pattern: >-
              ^([Aa][Uu][Tt][Oo]|[Dd][Rr][Yy]|[Cc][Oo][Ll][Dd]|[Ww][Aa][Rr][Mm]|[Ff][Aa][Nn])$
        - name: temp
          in: query
          description: 温度 (デフォルト 25℃)
          required: false
          schema:
            type: integer
        - name: fan
          in: query
          description: 風量 (デフォルト Auto)
          required: false
          schema:
            type: string
            pattern: '^([Aa][Uu][Tt][Oo]|[Ss][Ii][Ll][Ee][Nn][Tt]|[1-5])$'
        - name: swing
          in: query
          description: 風向上下させるかどうか (デフォルト true)
          required: false
          schema:
            type: boolean
        - name: powerful
          in: query
          description: パワフルモード (デフォルト false)
          required: false
          schema:
            type: boolean
        - name: timer
          in: query
          description: タイマーモード (デフォルト None)
          required: false
          schema:
            type: string
            pattern: '^([Nn][Oo][Nn][Ee]|[Oo][Nn]|[Oo][Ff]{2})$'
        - name: hour
          in: query
          description: タイマー時間
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 12
      responses:
        '204':
          description: 操作に成功
        default:
          description: 予期しないエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
servers:
  - url: /api/v1
components:
  schemas:
    Error:
      required:
        - status
        - message
      properties:
        status:
          description: HTTPステータスコード
          type: integer
        message:
          description: エラーメッセージ
          type: string
